#ifndef ERROR__H
#define ERROR__H 1

#define MAX_ERROR_STR 150

typedef enum {
	ST_OK,
	ST_ERROR_PUNTERO_NULO,
	ST_ERROR_CANTIDAD_ARGUMENTOS,
	ST_ERROR_MEMORIA_INVALIDA,
	ST_ERROR_ENTRADA_INVALIDA,
	ST_ERROR_FILE_INPUT_DEMASIADO_LARGO,
	ST_ERROR_FILE_OUTPUT_DEMASIADO_LARGO,
	ST_ERROR_ARGUMENTO_INVALIDO,
	ST_ERROR_INSTRUCCION_INVALIDA,
	ST_ERROR_LECTURA_ARCHIVO,
	ST_ERROR_CANTIDAD_DE_MEMORIA_INVALIDA,
	ST_ERROR_MEMORIA_INSUFICIENTE_ARCHIVO,
	ST_ERROR_CANTIDAD_PALABRAS_INVALIDA,
	ST_ERROR_SIMPLETRON,
	ST_ERROR_ARCHIVO,
	ST_HELP
} status_t;

#endif
